<?xml version="1.0"?>

<robot name="UMARU" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="scale" value="1"/>
  <xacro:property name="stack_length" value="0.04"/>
  <xacro:property name="stack_width" value="0.04"/>
  <xacro:property name="stack_tall" value="0.020"/>
  <xacro:property name="stack_mass" value="0.98"/>

  <xacro:macro name="empty_link" params="name">
    <link name="${name}">
      <inertial>
        <mass value="0"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0" />
      </inertial>
    </link>
  </xacro:macro>
  <xacro:macro name="stack_link" params="name">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
         <box size="${stack_length} ${stack_width} ${stack_tall}"/>
       </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
       <geometry>
          <box size="${stack_width} ${stack_width} ${stack_tall}"/>
       </geometry>
      </collision>
      <inertial>
       <mass value="stack_mass"/>
       <origin xyz="0 0 0"/>
       <inertia ixx="${stack_mass * (stack_width**2 + stack_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${stack_mass * (stack_width**2 + stack_tall**2) / 12}" iyz="0" 
               izz="${stack_mass * (stack_width**2 + stack_width**2) / 12}" />
      </inertial>
   </link>
  </xacro:macro>

  <material name="cyan">
    <color rgba="0 255 255 1"/>
  </material>

  <material name="yellow">
    <color rgba="255 255 0 1"/>
  </material>

  <xacro:property name="body_length" value="0.117"/>
  <xacro:property name="body_width" value="0.147"/>
  <xacro:property name="body_tall" value="0.176124"/>
  <xacro:property name="body_mass" value="1.80"/>
  <link name="body">
    <visual>
      <geometry>
        <box size="${body_length}  ${body_width} ${body_tall}"/>
      </geometry>
      <origin rpy="0 0 0"/>
      <material name="cyan"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length}  ${body_width} ${body_tall}"/>
      </geometry>
      <origin rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${body_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="${body_mass * (body_width**2 + body_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${body_mass * (body_length**2 + body_tall**2) / 12}" iyz="0" 
               izz="${body_mass * (body_width**2 + body_length**2) / 12}" />
    </inertial>
  </link>

  <xacro:property name="h_sho_length" value="0.065"/>
  <xacro:property name="h_sho_width" value="0.055"/>
  <xacro:property name="h_sho_tall" value="0.030"/>
  <xacro:property name="h_sho_mass" value="0.070"/>
  <link name="right_shoulder_horizontal">
    <visual>
      <geometry>
        <box size="${h_sho_length} ${h_sho_width} ${h_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 ${- h_sho_width / 2} 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${h_sho_length} ${h_sho_width} ${h_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 ${- h_sho_width / 2} 0"/>
    </collision>
    <inertial>
      <mass value="${h_sho_mass}"/>
      <origin xyz="0 ${- h_sho_width / 2} 0"/>
      <inertia ixx="${h_sho_mass * (h_sho_width**2 + h_sho_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${h_sho_mass * (h_sho_tall**2 + h_sho_length**2) / 12}" iyz="0" 
               izz="${h_sho_mass * (h_sho_width**2 + h_sho_length**2) / 12}" />
    </inertial>
  </link>
  <link name="left_shoulder_horizontal">
    <visual>
      <geometry>
         <box size="${h_sho_length} ${h_sho_width} ${h_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 ${h_sho_width / 2} 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${h_sho_length} ${h_sho_width} ${h_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 ${h_sho_width / 2} 0"/>
    </collision>
    <inertial>
      <mass value="${h_sho_mass}"/>
      <origin xyz="0 ${h_sho_width / 2} 0"/>
      <inertia ixx="${h_sho_mass * (h_sho_width**2 + h_sho_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${h_sho_mass * (h_sho_tall**2 + h_sho_length**2) / 12}" iyz="0" 
               izz="${h_sho_mass * (h_sho_width**2 + h_sho_length**2) / 12}" />
    </inertial>
  </link>
  
  <xacro:property name="v_sho_length" value="0.065"/>
  <xacro:property name="v_sho_width" value="0.030"/>
  <xacro:property name="v_sho_tall" value="0.020"/>
  <xacro:property name="v_sho_mass" value="0.070"/>
  <link name="right_shoulder_vertical">
    <visual>
      <geometry>
        <box size="${v_sho_length} ${v_sho_width} ${v_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- v_sho_tall / 2}"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${v_sho_length} ${v_sho_width} ${v_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- v_sho_tall / 2}"/>
    </collision>
    <inertial>
      <mass value="${v_sho_mass}"/>
      <origin xyz="0 0 ${- v_sho_tall / 2}"/>
      <inertia ixx="${v_sho_mass * (v_sho_width**2 + v_sho_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${v_sho_mass * (v_sho_length**2 + v_sho_tall**2) / 12}" iyz="0" 
               izz="${v_sho_mass * (v_sho_width**2 + v_sho_length**2) / 12}" />
    </inertial>
  </link>

  <link name="left_shoulder_vertical">
    <visual>
      <geometry>
        <box size="${v_sho_length} ${v_sho_width} ${v_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- v_sho_tall / 2}"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
         <box size="${v_sho_length} ${v_sho_width} ${v_sho_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- v_sho_tall / 2}"/>
    </collision>
    <inertial>
      <mass value="${v_sho_mass}"/>
      <origin xyz="0 0 ${- v_sho_tall / 2}"/>
      <inertia ixx="${v_sho_mass * (v_sho_width**2 + v_sho_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${v_sho_mass * (v_sho_length**2 + v_sho_tall**2) / 12}" iyz="0" 
               izz="${v_sho_mass * (v_sho_width**2 + v_sho_length**2) / 12}" />
    </inertial>
  </link>

  <xacro:property name="arm_length" value="0.038"/>
  <xacro:property name="arm_width" value="0.0402"/>
  <xacro:property name="arm_tall" value="0.156"/>
  <xacro:property name="arm_mass" value="0.120"/>
  <link name="right_arm">
    <visual>
      <geometry>
        <box size="${arm_length} ${arm_width} ${arm_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- arm_tall / 2}"/> 
      <material name="cyan"/>
    </visual>
    <collision>
      <geometry>
        <box size="${arm_length} ${arm_width} ${arm_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- arm_tall / 2}"/>
    </collision>
    <inertial>
      <mass value="${arm_mass}"/>
      <origin xyz="0 0 ${- arm_tall / 2}"/>
      <inertia ixx="${arm_mass * (arm_width**2 + arm_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${arm_mass * (arm_length**2 + arm_tall**2) / 12}" iyz="0" 
               izz="${arm_mass * (arm_width**2 + arm_length**2) / 12}" />
    </inertial>
  </link>

  <link name="left_arm">
    <visual>
      <geometry>
        <box size="${arm_length} ${arm_width} ${arm_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- arm_tall / 2}"/>
      <material name="cyan"/>
    </visual>
    <collision>
      <geometry>
        <box size="${arm_length} ${arm_width} ${arm_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- arm_tall / 2}"/>
    </collision>
    <inertial>
      <mass value="${arm_mass}"/>
      <origin xyz="0 0 ${- arm_tall / 2}"/>
      <inertia ixx="${arm_mass * (arm_width**2 + arm_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${arm_mass * (arm_length**2 + arm_tall**2) / 12}" iyz="0" 
               izz="${arm_mass * (arm_width**2 + arm_length**2) / 12}" />
    </inertial>
  </link>

  <xacro:property name="hand_length" value="0.0276"/>
  <xacro:property name="hand_width" value="0.0505"/>
  <xacro:property name="hand_tall" value="0.162"/>
  <xacro:property name="hand_mass" value="0.080"/>
  <link name="right_hand">
    <visual>
      <geometry>
        <box size="${hand_length} ${hand_width} ${hand_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- hand_tall / 2}"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${hand_length} ${hand_width} ${hand_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- hand_tall / 2}"/>
    </collision>
    <inertial>
      <mass value="${hand_mass}"/>
      <origin xyz="0 0 ${- hand_tall / 2}"/>
      <inertia ixx="${hand_mass * (hand_width**2 + hand_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${hand_mass * (hand_length**2 + hand_tall**2) / 12}" iyz="0" 
               izz="${hand_mass * (hand_width**2 + hand_length**2) / 12}" />
    </inertial>
  </link>
  <link name="left_hand">
    <visual>
      <geometry>
        <box size="${hand_length} ${hand_width} ${hand_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- hand_tall / 2}"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${hand_length} ${hand_width} ${hand_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- hand_tall / 2}"/>
    </collision>
    <inertial>
      <mass value="${hand_mass}"/>
      <origin xyz="0 0 ${- hand_tall / 2}"/>
      <inertia ixx="${hand_mass * (hand_width**2 + hand_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${hand_mass * (hand_length**2 + hand_tall**2) / 12}" iyz="0" 
               izz="${hand_mass * (hand_width**2 + hand_length**2) / 12}" />
    </inertial>
  </link>
  <!-- EMPTY LINK-->
  <xacro:empty_link name="head_tilt"/>
  <xacro:empty_link name="right_hip"/>
  <xacro:empty_link name="left_hip"/>


  <xacro:property name="leg_width" value="0.049"/>
  <xacro:property name="leg_tall" value="0.143"/>
  <xacro:property name="leg_mass" value="0.300"/>

<!-- HIP TEST WITH UPPER LEG EMPTY LINK -->
  <!-- <xacro:property name="hip_tall" value="0.162"/>
  <xacro:property name="hip_mass" value="0.120"/>
  <link name="right_hip">
    <visual>
      <geometry>
        <box size="${leg_width} ${leg_width} ${hip_tall}"/>
      </geometry>
      <origin xyz="0 0 ${- hip_tall/2}" rpy="0 0 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${leg_width} ${leg_width} ${hip_tall}"/>
      </geometry>
      <origin xyz="0 0 ${- hip_tall/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${hip_mass}"/>
      <origin xyz="0 0 ${- hip_tall/2}"/>
      <inertia ixx="${hip_mass * (leg_width**2 + hip_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${hip_mass * (leg_width**2 + hip_tall**2) / 12}" iyz="0" 
               izz="${hip_mass * (leg_width**2 + leg_width**2) / 12}" />
    </inertial>
  </link>
  <link name="left_hip">
    <visual>
      <geometry>
        <box size="${leg_width} ${leg_width} ${hip_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- hip_tall/2}"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${leg_width} ${leg_width} ${hip_tall}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${- hip_tall/2}"/>
    </collision>
    <inertial>
      <mass value="${hip_mass}"/>
      <origin xyz="0 0 ${- hip_tall/2}"/>
      <inertia ixx="${hip_mass * (leg_width**2 + hip_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${hip_mass * (leg_width**2 + hip_tall**2) / 12}" iyz="0" 
               izz="${hip_mass * (leg_width**2 + leg_width**2) / 12}" />
    </inertial>
  </link>  -->

  <link name="left_upper_leg">
    <visual>
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}"/>
      </geometry>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}"/>
      </geometry>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0"/>
    </collision>
   <inertial>
      <mass value="${leg_mass}"/>
      <origin xyz="0 0 ${-leg_tall/2}"/>
      <inertia ixx="${leg_mass* (leg_width**2 + leg_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${leg_mass * (leg_width**2 + leg_tall**2) / 12}" iyz="0" 
               izz="${leg_mass * (leg_width**2 + leg_width**2) / 12}" />
    </inertial>
  </link>

  <link name="right_upper_leg">
    <visual>
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}"/>
      </geometry>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0  0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}"/>
      </geometry>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0"/>
    </collision>
     <inertial>
      <mass value="${leg_mass}"/>
      <origin xyz="0 0 ${-leg_tall/2}"/>
      <inertia ixx="${leg_mass* (leg_width**2 + leg_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${leg_mass * (leg_width**2 + leg_tall**2) / 12}" iyz="0" 
               izz="${leg_mass * (leg_width**2 + leg_width**2) / 12}" />
    </inertial>
  </link>

  <xacro:stack_link name="right_hip_roll"/>
  <xacro:stack_link name="left_hip_roll"/>

  <link name="left_lower_leg">
    <visual>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0" />
      <material name="cyan" />
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0" />
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${leg_mass}"/>
      <origin xyz="0 0 ${- leg_tall/2}"/>
      <inertia ixx="${leg_mass* (leg_width**2 + leg_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${leg_mass * (leg_width**2 + leg_tall**2) / 12}" iyz="0" 
               izz="${leg_mass * (leg_width**2 + leg_width**2) / 12}" />
    </inertial>
  </link>

  <link name="right_lower_leg">
    <visual>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0" />
      <material name="cyan" />
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${- leg_tall/2}" rpy="0 0 0" />
      <geometry>
        <box size="${leg_width} ${leg_width} ${leg_tall}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${leg_mass}"/>
      <origin xyz="0 0 ${- leg_tall/2}"/>
      <inertia ixx="${leg_mass* (leg_width**2 + leg_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${leg_mass * (leg_width**2 + leg_tall**2) / 12}" iyz="0" 
               izz="${leg_mass * (leg_width**2 + leg_width**2) / 12}" />
    </inertial>
  </link>

  <xacro:property name="foot_length" value="0.11"/>
  <xacro:property name="foot_width" value="0.050"/>
  <xacro:property name="foot_tall" value="0.0031"/>
  <xacro:property name="foot_mass" value="0.4500"/>
  <!--foot Z origin is not correctly set (for test)-->
  <link name="left_foot">
    <visual>
      <origin xyz="0 0 ${-foot_tall/2 }" rpy="0 0 0" />
      <material name="cyan" />
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_tall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-foot_tall/2}" rpy="0 0 0" />
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_tall}" />
      </geometry>
    </collision>
   <inertial>
      <mass value="${foot_mass}"/>
      <origin xyz="0 0 ${-foot_tall/2 }"/>
      <inertia ixx="${foot_mass* (foot_width**2 + foot_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${foot_mass* (foot_length**2 + foot_tall**2) / 12}" iyz="0" 
               izz="${foot_mass* (foot_width**2 + foot_length**2) / 12}" />
    </inertial>
  </link>

  <link name="right_foot">
    <visual>
      <origin xyz="0 0 ${-foot_tall/2 }" rpy="0 0 0" />
      <material name="cyan" />
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_tall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${-foot_tall/2 }" rpy="0 0 0" />
      <geometry>
        <box size="${foot_length} ${foot_width} ${foot_tall}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${foot_mass}"/>
      <origin xyz="0 0 ${-foot_tall/2 }"/>
      <inertia ixx="${foot_mass* (foot_width**2 + foot_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${foot_mass* (foot_length**2 + foot_tall**2) / 12}" iyz="0" 
               izz="${foot_mass* (foot_width**2 + foot_length**2) / 12}" />
    </inertial>
  </link>

  <xacro:stack_link name="right_ankle_roll"/>
  <xacro:stack_link name="left_ankle_roll"/>

  <xacro:property name="neck_length" value="0.031"/>
  <xacro:property name="neck_width" value="0.046"/>
  <xacro:property name="neck_tall" value="0.058"/>
  <xacro:property name="neck_mass" value="0.180"/>
  <link name="neck">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <material name="yellow" />
      <geometry>
        <box size="${neck_length} ${neck_width} ${neck_tall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${neck_length} ${neck_width} ${neck_tall}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${neck_mass}"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="${neck_mass * (neck_width**2 + neck_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${neck_mass * (neck_length**2 + neck_tall**2) / 12}" iyz="0" 
               izz="${neck_mass * (neck_width**2 + neck_length**2) / 12}" />
    </inertial>
  </link>

  <xacro:property name="head_length" value="0.02"/>
  <xacro:property name="head_width" value="0.092"/>
  <xacro:property name="head_tall" value="0.055"/>
  <xacro:property name="head_mass" value="0.05"/>

  <link name="head">
    <visual>
      <origin xyz="0 0 ${head_tall / 2}" rpy="0 0 0" />
      <material name="cyan" />
      <geometry>
        <box size="${head_length} ${head_width} ${head_tall}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${head_tall / 2}" rpy="0 0 0" />
      <geometry>
        <box size="${head_length} ${head_width} ${head_tall}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${head_mass}"/>
      <origin xyz="0 0 ${head_tall / 2}"/>
      <inertia ixx="${head_mass * (head_width**2 + head_tall**2) / 12}" ixy="0" ixz="0" 
               iyy="${head_mass * (head_length**2 + head_tall**2) / 12}" iyz="0" 
               izz="${head_mass * (head_width**2 + head_length**2) / 12}" />
    </inertial>
  </link>

<!--JOINT-->
  <joint name="R_SHO_PITCH" type="revolute" > <!-- JOINT_ID = 1 -->
    <axis xyz="0 -1 0"/>
    <parent link="body"/>
    <child link="right_shoulder_horizontal"/>
    <origin xyz="0 ${-body_width / 2} ${(body_tall / 2) - (h_sho_tall/2)}"/>
    <limit effort="1000.0" lower="${-pi}" upper="${pi}" velocity="0.5" />
  </joint>

  <joint name="L_SHO_PITCH" type="revolute"> <!-- JOINT_ID = 2 -->
    <axis xyz="0 -1 0"/>
    <parent link="body"/>
    <child link="left_shoulder_horizontal"/>
    <origin xyz="0 ${body_width / 2} ${(body_tall / 2) - (h_sho_tall/2)}"/>
    <limit effort="1000.0" lower="${-pi}" upper="${pi}" velocity="0.5" />
  </joint>

  <joint name="R_SHO_ROLL" type="revolute" > <!-- JOINT_ID = 3 -->
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5" />
    <axis xyz="-1 0 0"/>
    <parent link="right_shoulder_vertical"/>
    <child link="right_arm"/>
    <origin xyz="0 0 ${-v_sho_tall/2}"/>
  </joint>

  <joint name="L_SHO_ROLL" type="revolute" > <!-- JOINT_ID = 4 -->
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="${pi/2}" velocity="0.5"/>
    <parent link="left_shoulder_vertical"/>
    <child link="left_arm"/>
    <origin xyz="0 0 ${-v_sho_tall/2}"/>
  </joint>

  <joint name="R_ELBOW" type="revolute"> <!-- JOINT_ID = 5 -->
    <axis xyz="0 -1 0"/>
    <limit effort="1000.0" lower="${-1.5*pi}" upper="${1.5*pi}" velocity="0.5"/>
    <parent link="right_arm"/>
    <child link="right_hand"/>
    <origin xyz="0 0 ${-arm_tall}"/>
  </joint>

  <joint name="L_ELBOW" type="revolute"> <!-- JOINT_ID = 6 -->
    <axis xyz="0 -1 0"/>
    <limit effort="1000.0" lower="${-1.5*pi}" upper="${1.5*pi}" velocity="0.5"/>
    <parent link="left_arm"/>
    <child link="left_hand"/>
    <origin xyz="0 0 ${-arm_tall}"/>
  </joint>

  <joint name="R_HIP_ROLL" type="revolute"> <!-- JOINT_ID = 7-->
    <parent link="right_hip" />
    <child link="right_hip_roll" />
    <axis xyz="-1 0 0" />
    <origin xyz="0 0 0" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="L_HIP_ROLL" type="revolute"> <!-- JOINT_ID = 8-->
    <parent link="left_hip" />
    <child link="left_hip_roll" />
    <axis xyz="1 0 0" />
    <origin xyz="0 0 0" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="R_HIP_YAW" type="revolute"> <!-- JOINT_ID = 9 -->
    <parent link="body"/>
    <child link="right_hip"/>
    <origin xyz="0 ${-body_width/2 + leg_width/1.5} ${-body_tall/2}"/>
    <axis xyz="0 0 -1" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi/2}" upper="${pi}" />
  </joint>

  <joint name="L_HIP_YAW" type="revolute"> <!-- JOINT_ID = 10 -->
    <parent link="body"/>
    <child link="left_hip"/>
    <origin xyz="0 ${body_width/2 - leg_width/1.5} ${-body_tall/2}"/>
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi/2}" upper="${pi}" /> 
  </joint>

  <joint name="R_HIP_PITCH" type="revolute"> <!-- JOINT_ID = 11-->
    <parent link="right_hip_roll" />
    <child link="right_upper_leg" />
    <axis xyz="0 -1 0" />
    <origin xyz="0 0 0" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="L_HIP_PITCH" type="revolute"> <!-- JOINT_ID = 12-->
    <parent link="left_hip_roll" />
    <child link="left_upper_leg" />
    <axis xyz="0 -1 0" />
    <origin xyz="0 0 0" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="R_KNEE" type="revolute"> <!-- JOINT_ID = 13 -->
    <parent link="right_upper_leg" />
    <child link="right_lower_leg" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${- leg_tall}" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>
 
  <joint name="L_KNEE" type="revolute"> <!-- JOINT_ID = 14 -->
    <parent link="left_upper_leg" />
    <child link="left_lower_leg" />
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${- leg_tall}" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="R_ANK_ROLL" type="revolute"> <!-- JOINT_ID = 15 -->
    <parent link="right_lower_leg" />
    <child link="right_ankle_roll" />
    <axis xyz="-1 0 0" />
    <origin xyz="0 0 ${- leg_tall + (stack_tall/2)}" />
    <limit effort="1000.0" velocity="0.5" lower="0" upper="${pi}"/>
  </joint>

  <joint name="L_ANK_ROLL" type="revolute"> <!-- JOINT_ID = 16 -->
    <parent link="left_lower_leg" />
    <child link="left_ankle_roll" />
    <axis xyz="1 0 0" />
    <origin xyz="0 0 ${- leg_tall + (stack_tall/2)}" />
    <limit effort="1000.0" velocity="0.5" lower="0" upper="${pi}"/>
  </joint>

  <joint name="R_ANK_PITCH" type="revolute"> <!-- JOINT_ID = 17 -->
    <parent link="right_ankle_roll" />
    <child link="right_foot" />
    <axis xyz="0 -1 0" />
    <origin xyz="0 0 ${-stack_tall}" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
    <dynamics damping="1000" friction="1000"/>
  </joint>

  <joint name="L_ANK_PITCH" type="revolute"> <!-- JOINT_ID = 18 -->
    <parent link="left_ankle_roll" />
    <child link="left_foot" />
    <axis xyz="0 -1 0" />
    <origin xyz="0 0 ${-stack_tall}" />
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="HEAD_PAN" type="revolute"> <!-- JOINT_ID = 19 -->
    <parent link="body"/>
    <child link="neck"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 ${(body_tall/2) + (neck_tall/2)}"/>
    <limit effort="1000.0" velocity="0.5" lower="${-pi}" upper="${pi}"/>
  </joint>

  <joint name="HEAD_TILT" type="revolute"> <!-- JOINT_ID = 20 -->
    <parent link="head_tilt"/>
    <child link="head"/>
    <axis xyz="0 1 0"/>
    <origin xyz="0 0 0"/>
    <limit effort="1000.0" velocity="0.5" lower="${-4*pi/10}" upper="${4*pi/10}"/> 
  </joint>

<!--Fixed Joint-->
  <joint name="RIGHT_SHO" type="fixed"> 
    <parent link="right_shoulder_horizontal"/>
    <child link="right_shoulder_vertical"/>
    <origin xyz="0 ${-h_sho_width/2} ${-h_sho_tall/2}"/>
  </joint>

  <joint name="LEFT_SHO" type="fixed"> 
    <parent link="left_shoulder_horizontal"/>
    <child link="left_shoulder_vertical"/>
    <origin xyz="0 ${h_sho_width/2} ${-h_sho_tall/2}"/>
  </joint>

  <joint name="NECK_TO_HEAD" type="fixed">
    <parent link="neck"/>
    <child link="head_tilt"/>
    <origin xyz="${neck_length/2} 0 0"/>
  </joint>

</robot>